#include <raylib.h>

	

#define WIN_HEIGHT 600
#define WIN_WIDTH 800

int 
main()
{
	SetConfigFlags(FLAG_WINDOW_RESIZABLE);
	InitWindow(WIN_WIDTH, WIN_HEIGHT, "NEOFISH");
	
	Camera camera = { 0 };
	camera.position = (Vector3){ 6.0f, 6.0f, 6.0f };
	camera.target = (Vector3){ 0.0f, 2.0f, 0.0f };
	camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };
	camera.fovy = 45.0f;
	camera.projection = CAMERA_PERSPECTIVE;
	
	Model model = LoadModel("assets/fish/first.glb");
	Vector3 position = { 0.0f, 0.0f, 0.0f };

	while (!WindowShouldClose()) {
		UpdateCamera(&camera, CAMERA_ORBITAL);

		BeginDrawing();
		
		ClearBackground(BLACK);
		BeginMode3D(camera);
		DrawModel(model, position, 1.0f, WHITE);
		DrawGrid(10, 1.0f);
		EndMode3D();

		EndDrawing();
	}

	UnloadModel(model); 
	CloseWindow();
	
	return 0;
}
